name: MLOps Model Quality
description: >-
  -
author: wseol test
specification_version: 1.0
prototype_version: 0.1
date: "2023-03-29"

environment_variables:
  DEV_MODE:
    default: True
    description: >-
      Flag to indicate if the AMP should run on sample dataset
      (True) to facilitate efficient project development or the full dataset (False).
    required: True

feature_dependencies:
  - model_metrics

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard
    version: 2022.11
    addons: ["Spark 3.2.0 - CDE 1.17 - HOTFIX-1"]

tasks:
  - type: run_session
    name: Install Dependencies
    script: scripts/1_install_dependencies.py
    short_summary: 1. Install Dependencies
    long_summary: Install dependencies, set environment variables, and upload data
    memory: 16
    cpu: 8

  - type: run_session
    name: Load CSV to Hive
    script: scripts/2_load_csv_to_hive.py
    short_summary: 2. Load CSV to Hive
    long_summary: Loading CSV to Hive using Spark
    memory: 16
    cpu: 8

  - type: run_session
    name: Prepare Data
    script: scripts/3_prepare_data.py
    short_summary: 3. Prepare Data
    long_summary: Preparing data for model training
    memory: 16
    cpu: 8

  - type: run_session
    name: Train and save Model
    script: scripts/4_train_and_save_model.py
    short_summary: 4. Train and save Model
    long_summary: Training model with experiments. Saving the model pipeline
    memory: 16
    cpu: 8

  - type: create_model
    name: Flight_Cancellation_Prediction
    entity_label: pr_model
    description: .
    short_summary: Create the Cancellation Prediction model API endpoint
    access_key_environment_variable: SHTM_ACCESS_KEY
    default_resources:
      cpu: 8
      memory: 16
    default_replication_policy:
      type: fixed
      num_replicas: 1

  - type: build_model
    name: Flight_Cancellation_Prediction
    entity_label: pr_model
    target_file_path: scripts/6_predict.py
    target_function_name: predict
    examples:
      - request:
          {
            "record":
              {
                "flightnum": 1628,
                "crsdeptime": 715,
                "crsarrtime": 820,
                "crselapsedtime": 65.0,
                "distance": 224.0,
                "hour": 7,
                "week": 37
              },
          }

  - type: deploy_model
    name: Price Regressor
    entity_label: pr_model
    memory: 16
    cpu: 8

  - type: run_session
    name: Add noise to data
    script: scripts/8_add_noise_data.py
    short_summary: 8. Adding noise to data for mimicking Data Drift and Model Decay
    memory: 16
    cpu: 8

  - type: start_application
    name: Run Simulation
    script: scripts/9_simulate.py
    memory: 16
    cpu: 8